version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_loan_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loan-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loan_network
  test:
    build:
      context: .
      target: test_img
    volumes:
      - ./:/src
  dev: &dev
    build:
      context: .
      target: dev_img
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
    links:
      - postgres

  prod:
    <<: *dev
    build:
      context: .
      target: prod_img
volumes:
  postgres_data:
    driver: local

networks:
  loan_network:
    driver: bridge
