version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_loan_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loan-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loan_network

volumes:
  postgres_data:
    driver: local

networks:
  loan_network:
    driver: bridge
